Fix calling qdbus by using qt5-current name qdbus-qt5
Summary:
Due to Qt not providing OOTB support for parallel installation of different
base versions (like Qt4 and Qt5), Linux distributions have separated into
different approaches how to name the Qt tools like qmake and qdbus.
Many use -qt4 and -qt5 suffixes and link the normal name to a variant, e.g.
controlled by a custom tool qtchooser. Others kept the Qt4 versions to stay
with the names, and only added a suffix -qt5 to the new ones.

Test Plan:
There is no longer a warning about missing qtdbus in the embedded konsole on
opening. The commands like search! & Co. work again.

Reviewers: #kdevelop, lbeltrame, fvogt, jriddell, kfunk

Subscribers: kfunk, kdevelop-devel

Tags: #kdevelop

Differential Revision: https://phabricator.kde.org/D15606

diff --git a/app/kdevelop! b/app/kdevelop!
--- a/app/kdevelop!
+++ b/app/kdevelop!
@@ -43,8 +43,9 @@ if [ "$(echo $KDEV_ATTACHED_PID | wc -w | sed 's/ //g')" != 1 ]; then
     exit 6
 fi
 
-if ! [ "$(which qdbus)" ]; then
-    echo "Error: The qdbus utility is missing."
+# find qdbus, try also alternative name qdbus-qt5
+if ! [ "$(which qdbus-qt5 2> /dev/null)$(which qdbus 2> /dev/null)" ]; then
+    echo "Error: The qdbus (or qdbus-qt5) utility is missing."
     exit 7
 fi
 
